/**
 * Tabs ("onglets") used as `Onglet` in request signatures.
 * The server checks that the tab is allowed for the user before answering.
 */
export const Tab = {
  HOME:                  "ACCUEIL",
  TIMETABLE:             "COURS.EDT.EDT_LISTE",
  TIMETABLE_GRID:        "COURS.EDT.EDT_GRILLE",
  CANCELED_LESSONS:      "COURS.COURSANNULES",
  LESSONS_SUMMARY:       "COURS.RECAPCOURS",
  LATEST_GRADES:         "NOTATION.DERNIERESNOTES",
  TRANSCRIPT:            "NOTATION.RELEVENOTES",
  REPORT_CARD:           "NOTATION.BULLETIN",
  MULTI_YEAR_REPORT:     "NOTATION.BULLETINMULTIANNEES",
  SKILLS:                "NOTATION.SAISIECOMPETENCES",
  SKILLS_REPORT:         "NOTATION.RELEVEPERIODIQUECOMPETENCES",
  ABSENCES:              "VIESCOLAIRE.RELEVEABSENCE",
  SCHOOLING:             "VIESCOLAIRE.SCOLARITE",
  FOLLOW_UPS:            "VIESCOLAIRE.SUIVIS",
  SCHOOL_CALENDAR:       "VIESCOLAIRE.CALENDRIERSCOLAIRE",
  LESSON_CONTENTS:       "ENSEIGNEMENTS.PROGRAMMECONTENU",
  HOMEWORK:              "ENSEIGNEMENTS.PROGRAMMETAF",
  RESOURCES:             "ENSEIGNEMENTS.RESSOURCESPEDAGOGIQUES",
  SUPERVISED_EXAMS:      "ENSEIGNEMENTS.DEVOIRSURVEILLE",
  TEACHING_EVALUATION:   "ENSEIGNEMENTS.EVALUATIONENSEIGNEMENT",
  COMPANIES:             "STAGE.OFFRESDESTAGE",
  INTERNSHIP_FILE:       "STAGE.SAISIEDOSSIERSTAGE",
  INTERNSHIP:            "STAGE.FICHESTAGE",
  INTERNSHIP_FOLLOW_UPS: "STAGE.SUIVIS",
  NEWS:                  "COMMUNICATION.INFOSSONDAGES",
  ACCOUNT:               "INFOSPERSO.COMPTE",
  DOCUMENTS:             "INFOSPERSO.DOCUMENTSTELECHARGER"
} as const;

export type TabId = typeof Tab[keyof typeof Tab];
